name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: '3.8'
      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: "apt-get update -y && apt-get install -y python3-dev build-essential"
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: html-docs
          path: docs/_build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@master
        if: github.ref == 'refs/heads/main'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html